# Generated by Django 4.2.11 on 2024-03-21 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainhp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mainhp',
            name='image',
        ),
        migrations.AlterField(
            model_name='mainhp',
            name='quote',
            field=models.CharField(max_length=150),
        ),
    ]
