# Generated by Django 4.2.11 on 2024-03-20 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('benefits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='benefits',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
