# Generated by Django 4.2.11 on 2024-03-07 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='duration',
            field=models.TextField(blank=True),
        ),
    ]
