# Generated by Django 4.2.11 on 2024-03-07 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_post_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='serves',
            field=models.IntegerField(choices=[(0, 'Serves 1'), (1, 'Serves 2'), (2, 'Serves 2 - 4')], default=0),
        ),
    ]
