# Generated by Django 4.2.11 on 2024-03-07 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_post_ingredients_post_source_of'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='method',
            field=models.TextField(blank=True),
        ),
    ]
