# Generated by Django 4.2.11 on 2024-03-08 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_post_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='duration',
            field=models.TextField(default=False, max_length=20),
        ),
    ]
