# Generated by Django 4.2.11 on 2024-03-08 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0010_alter_post_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='excerpt',
            field=models.TextField(default=False, max_length=200),
        ),
        migrations.AlterField(
            model_name='post',
            name='ingredients',
            field=models.TextField(default=False, max_length=300),
        ),
        migrations.AlterField(
            model_name='post',
            name='method',
            field=models.TextField(default=False, max_length=500),
        ),
        migrations.AlterField(
            model_name='post',
            name='source_of',
            field=models.TextField(default=False, max_length=50),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
