# Generated by Django 4.2.11 on 2024-03-08 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0011_alter_post_excerpt_alter_post_ingredients_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='duration',
            field=models.TextField(max_length=20),
        ),
        migrations.AlterField(
            model_name='post',
            name='excerpt',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='ingredients',
            field=models.TextField(max_length=300),
        ),
        migrations.AlterField(
            model_name='post',
            name='method',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='post',
            name='source_of',
            field=models.TextField(max_length=50),
        ),
    ]
