# Generated by Django 4.2.11 on 2024-03-25 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0018_rename_image_post_featured_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.IntegerField(choices=[(0, 'Breakfast'), (1, 'Dinner'), (2, 'Desserts'), (3, 'Drinks')], default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='excerpt',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='ingredients',
            field=models.TextField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='post',
            name='method',
            field=models.TextField(max_length=2000),
        ),
    ]
